### ISSUE TITLE
Interpolazione di Stringhe

### ISSUE THREAD

**Issue by tommaso1974** [sniperwolf/The-Little-Book-on-CoffeeScript-Italiano#2]
Ciao

E' la prima volta che apro un'issue su githup, per cui spero di non commettere errori.
Leggendo la tua traduzione del libro mi sono accorto che in questa sezione definisci la variabile
colore_preferito però poi poche righe più sotto indiche #{favorite_color}.

**Comment by sniperwolf** [comment]
Ciao Tommaso,

hai ragione, modifico il file. Grazie per il supporto ;)
